name          'example42-monitor'
version       '2.0.0'
source        'https://github.com/example42/puppet-monitor'
author        'Alessandro Franceschi'
license       'Apache 2.0'
project_page  'http://www.example42.com'
summary       'Puppet monitoring abstraction meta module'
description   'This module provides abstraction defines to monitor resources managed by Puppet modules. It is used in the Example42 modules set but can be imported and used in other setups. According to the monitor tool used it may have the relevant module as dependency'

dependency 'example42/puppi', '>=2.0.0'
